before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy key ()
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_production:
  type: deploy
  environment:
    name: production
    url: https://mytelecom.pt/
  script:
    - ssh mytelecom@mytelecom.pt -p 1082 "cd ~/public_html/mytelecom && git fetch origin main && git reset --hard origin/main && exit"
  only:
    - main
